import { ConvexHttpClient } from "convex/browser";
// Generated by `npx convex dev` from ../../../convex — run that once before
// starting the poller so this module exists.
import { api } from "../../../convex/_generated/api.js";
import type { Id } from "../../../convex/_generated/dataModel.js";
import { config } from "./config.js";
import { startControlServer, type PollState, type SessionStartResult } from "./controlServer.js";
import { DdpaiClient, parseCameraTime } from "./ddpaiClient.js";
import { parseGpsFile } from "./nmeaTarParser.js";
import { insertAccelSamplesChunked } from "./accelBatching.js";
import { createLogger } from "./logger.js";
import { saveFile, deleteFile } from "./storage.js";

const convex = new ConvexHttpClient(config.convexUrl);
const log = createLogger(convex);

let state: PollState = "idle";

// The poller has no fixed camera anymore — it idles until a network watcher
// script (e.g. on the Raspberry Pi) tells it which camera's Wi-Fi it just
// joined, via POST /session/start. Only one session is active at a time,
// matching the physical reality that the host can only be on one camera's
// network at once.
interface CameraSession {
  cameraId: Id<"cameras">;
  camUrl: string;
  client: DdpaiClient;
}

let session: CameraSession | null = null;

function startSessionForCamera(camera: { _id: Id<"cameras">; name: string; camUrl: string }): void {
  session = {
    cameraId: camera._id,
    camUrl: camera.camUrl,
    client: new DdpaiClient({ camUrl: camera.camUrl, timeoutMs: config.timeoutMs }),
  };
  console.log(`session started: camera ${camera.name}`);
  pollOnce().catch((err) => console.error("session-start poll failed", err));
}

async function startSession(ssid: string): Promise<SessionStartResult> {
  const camera = await convex.query(api.cameras.getBySsid, { ssid });
  if (!camera) {
    return { status: "unknown_ssid" };
  }
  startSessionForCamera(camera);
  return { status: "started" };
}

function endSession(): void {
  if (session) {
    console.log(`session ended: camera ${session.cameraId}`);
  }
  session = null;
}

async function pollOnce(): Promise<void> {
  if (state === "polling") return;
  state = "polling";
  try {
    await runPollCycle();
  } finally {
    state = "idle";
  }
}

async function runPollCycle(): Promise<void> {
  if (!session) {
    console.log("no active camera session, idle");
    return;
  }
  const { cameraId, client: camera } = session;

  await log.info("poll started");

  const reachable = await camera.isReachable();
  if (!reachable) {
    await log.warn("camera unreachable");
    await convex.mutation(api.cameraStatus.report, {
      cameraId,
      connected: false,
      lastError: "camera unreachable",
    });
    return;
  }

  try {
    await camera.authenticate();
    await log.info("authenticated with camera");
    await convex.mutation(api.cameraStatus.report, {
      cameraId,
      connected: true,
    });

    // GPS files are small, so fetch them first/always. Recordings are only
    // listed here (metadata) — the actual video download happens on demand
    // when requested from the UI, via processQueuedDownloads below.
    const gpsDownloaded = await syncGpsFiles(session);
    const playbackListed = await syncPlaybackMetadata(session);
    const eventsListed = await syncEventsMetadata(session);
    const queueStats = await processQueuedDownloads(session);

    await log.info("poll completed", {
      gpsFiles: gpsDownloaded,
      listed: playbackListed + eventsListed,
      downloaded: queueStats.downloaded,
      failed: queueStats.failed,
    });
  } catch (err) {
    const message = err instanceof Error ? err.message : String(err);
    await log.error("poll cycle failed", { error: message });
    await convex.mutation(api.cameraStatus.report, {
      cameraId,
      connected: false,
      lastError: message,
    });
  }
}

// Downloads a file while reporting progress to Convex (for the Recordings
// screen) and the console, throttled to ~every 2s so large/slow transfers
// don't spam either. Marks the row completed/failed when done.
//
// The camera's embedded HTTP server appears to need a brief cooldown
// between requests — back-to-back downloads reliably alternate
// success/ETIMEDOUT (observed consistently on real hardware: every other
// small GPS file times out). A fixed delay before each attempt, plus a
// couple of retries, works around this rather than treating it as fatal.
const DOWNLOAD_COOLDOWN_MS = 1_000;
const MAX_DOWNLOAD_ATTEMPTS = 3;

function sleep(ms: number): Promise<void> {
  return new Promise((resolve) => setTimeout(resolve, ms));
}

async function downloadWithProgress(camera: DdpaiClient, filename: string): Promise<Buffer> {
  let lastError: unknown;

  for (let attempt = 1; attempt <= MAX_DOWNLOAD_ATTEMPTS; attempt++) {
    await sleep(DOWNLOAD_COOLDOWN_MS);

    let lastReportedAt = 0;
    let lastReportedBytes = 0;
    try {
      const data = await camera.downloadFile(filename, (info) => {
        const now = Date.now();
        const elapsedMs = now - lastReportedAt;
        if (elapsedMs < 2_000) return;

        const bytesPerSecond =
          lastReportedAt === 0
            ? undefined
            : Math.round(((info.bytesReceived - lastReportedBytes) / elapsedMs) * 1000);
        lastReportedAt = now;
        lastReportedBytes = info.bytesReceived;

        convex
          .mutation(api.downloadProgress.report, {
            filename,
            bytesReceived: info.bytesReceived,
            totalBytes: info.totalBytes,
            bytesPerSecond,
            status: "downloading",
          })
          .catch((err) => console.error("failed to report download progress", err));
        const mbReceived = (info.bytesReceived / 1_000_000).toFixed(1);
        const pct = info.totalBytes
          ? ` (${Math.round((info.bytesReceived / info.totalBytes) * 100)}%)`
          : "";
        const speed = bytesPerSecond ? ` @ ${(bytesPerSecond / 1_000).toFixed(0)}KB/s` : "";
        console.log(`[progress] ${filename}: ${mbReceived}MB${pct}${speed}`);
      });

      await convex.mutation(api.downloadProgress.report, {
        filename,
        bytesReceived: data.length,
        totalBytes: data.length,
        status: "completed",
      });
      return data;
    } catch (err) {
      lastError = err;
      const message = err instanceof Error ? err.message : String(err);
      console.warn(`download attempt ${attempt}/${MAX_DOWNLOAD_ATTEMPTS} for ${filename} failed: ${message}`);
    }
  }

  await convex.mutation(api.downloadProgress.report, {
    filename,
    bytesReceived: 0,
    status: "failed",
    error: lastError instanceof Error ? lastError.message : String(lastError),
  });
  throw lastError;
}

async function syncGpsFiles(session: CameraSession): Promise<number> {
  const { cameraId, client: camera } = session;
  const gpsEntries = await camera.listGpsFiles();
  await log.info(`found ${gpsEntries.length} gps files`);

  // The camera's GPS list isn't reliably linked to recordings via
  // `parentfile` — the reference client downloads every GPS file
  // unconditionally rather than gating on a match, so we do the same and
  // only attach a recordingId when a match happens to exist.
  let downloaded = 0;
  let matched = 0;
  for (const entry of gpsEntries) {
    const existing = await convex.query(api.gpsFiles.getByFilename, {
      cameraId,
      filename: entry.name,
    });
    if (existing) continue;

    // The camera has no delete API, so a previously deleted (journeys
    // deleteRange) file is still in its listing — skip it rather than
    // silently reimporting what the user just removed.
    if (await convex.query(api.deletedFiles.isDeleted, { cameraId, filename: entry.name })) continue;

    try {
      const recording = await convex.query(api.recordings.getByFilename, {
        cameraId,
        filename: entry.parentfile,
      });
      if (recording) matched += 1;

      const data = await downloadWithProgress(camera, entry.name);
      const filePath = await saveFile("gps", entry.name, data, cameraId);

      const gpsFileId = await convex.mutation(api.gpsFiles.upsert, {
        cameraId,
        recordingId: recording?._id,
        filename: entry.name,
        filePath,
      });
      downloaded += 1;

      const { fixes, accelSamples } = await parseGpsFile(data);
      if (fixes.length > 0) {
        await convex.mutation(api.gpsFixes.insertBatch, {
          gpsFileId,
          recordingId: recording?._id,
          cameraId,
          fixes,
        });
        await convex.mutation(api.gpsFiles.markParsed, { id: gpsFileId });
        await log.info(`parsed ${fixes.length} gps fixes from ${entry.name}`);
      } else {
        await log.warn(`${entry.name} contained no parseable GPS fixes — kept as raw file only`);
      }

      if (accelSamples.length > 0) {
        await insertAccelSamplesChunked(convex, gpsFileId, recording?._id, accelSamples);
        const peakG = Math.max(...accelSamples.map((s) => s.magnitudeG));
        await log.info(
          `parsed ${accelSamples.length} accelerometer samples from ${entry.name} (peak ${peakG.toFixed(2)}g)`,
        );
      }

      // The raw file's only value was as input to the parse above — once
      // fixes/accelSamples are safely in Convex, delete it from disk to
      // avoid keeping every historical GPS file around indefinitely.
      // Skipped when no fixes were extracted (kept as raw file only, since
      // that's all the data we have for it).
      if (fixes.length > 0) {
        await deleteFile(filePath);
        await convex.mutation(api.gpsFiles.clearFilePath, { id: gpsFileId });
      }
    } catch (err) {
      await log.error(`failed to download gps file ${entry.name}`, {
        error: err instanceof Error ? err.message : String(err),
      });
    }
  }

  await log.info(`gps sync: downloaded ${downloaded}, matched to a recording: ${matched}`);
  return downloaded;
}

// Lists continuous/timelapse recordings as metadata only — no video is
// downloaded here. Downloading happens on demand via requestDownload from
// the Recordings screen, processed by processQueuedDownloads below.
async function syncPlaybackMetadata(session: CameraSession): Promise<number> {
  const { cameraId, client: camera } = session;
  const entries = await camera.listPlayback();
  await log.info(`found ${entries.length} playback recordings`);

  let listed = 0;
  for (const entry of entries) {
    const existing = await convex.query(api.recordings.getByFilename, {
      cameraId,
      filename: entry.name,
    });
    if (existing) continue;
    if (await convex.query(api.deletedFiles.isDeleted, { cameraId, filename: entry.name })) continue;

    const startTime = parseCameraTime(entry.starttime);
    const endTime = parseCameraTime(entry.endtime);

    await convex.mutation(api.recordings.upsertMetadata, {
      cameraId,
      kind: "continuous",
      filename: entry.name,
      startTime,
      durationSeconds: Math.max(0, Math.round((endTime - startTime) / 1000)),
      sizeBytes: entry.size !== undefined ? Number(entry.size) : undefined,
    });
    listed += 1;
  }

  return listed;
}

// Lists event recordings as metadata and auto-downloads their (small)
// thumbnail for browsing, but leaves the main video for on-demand download
// like continuous recordings.
async function syncEventsMetadata(session: CameraSession): Promise<number> {
  const { cameraId, client: camera } = session;
  const entries = await camera.listEvents();
  await log.info(`found ${entries.length} event recordings`);

  let listed = 0;
  for (const entry of entries) {
    const existing = await convex.query(api.recordings.getByFilename, {
      cameraId,
      filename: entry.bvideoname,
    });
    if (existing) continue;
    if (await convex.query(api.deletedFiles.isDeleted, { cameraId, filename: entry.bvideoname })) continue;

    const startTime = parseCameraTime(entry.bstarttime);
    const endTime = parseCameraTime(entry.bendtime);

    const recordingId = await convex.mutation(api.recordings.upsertMetadata, {
      cameraId,
      kind: "event",
      filename: entry.bvideoname,
      startTime,
      durationSeconds: Math.max(0, Math.round((endTime - startTime) / 1000)),
      sizeBytes: entry.bvideosize !== undefined ? Number(entry.bvideosize) : undefined,
    });

    await convex.mutation(api.events.create, {
      recordingId,
      type: "other",
      timestamp: startTime,
    });
    listed += 1;

    if (entry.imgname) {
      try {
        const thumbData = await downloadWithProgress(camera, entry.imgname);
        const thumbnailPath = await saveFile("thumbnails", entry.imgname, thumbData, cameraId);
        await convex.mutation(api.recordings.setThumbnail, {
          id: recordingId,
          thumbnailPath,
        });
      } catch (err) {
        await log.error(`failed to download thumbnail ${entry.imgname}`, {
          error: err instanceof Error ? err.message : String(err),
        });
      }
    }
  }

  return listed;
}

// Downloads any recordings the user requested from the Recordings screen
// (status "queued"), regardless of kind. Only recordings belonging to the
// currently active camera are processed here — a recording queued while a
// different camera's network was active physically only exists on that
// other camera's server, and will get picked up next time its session runs.
async function processQueuedDownloads(
  session: CameraSession,
): Promise<{ downloaded: number; failed: number }> {
  const { cameraId, client: camera } = session;
  const allQueued = await convex.query(api.recordings.listQueued, {});
  const queued = allQueued.filter((r) => r.cameraId === cameraId);
  if (queued.length > 0) {
    await log.info(`processing ${queued.length} requested downloads`);
  }

  let downloaded = 0;
  let failed = 0;
  for (const recording of queued) {
    await convex.mutation(api.recordings.markDownloading, { id: recording._id });
    try {
      await log.info(`downloading requested recording ${recording.filename}`);
      const data = await downloadWithProgress(camera, recording.filename);
      const filePath = await saveFile("videos", recording.filename, data, cameraId);
      await convex.mutation(api.recordings.markDownloaded, { id: recording._id, filePath });
      downloaded += 1;
      await log.info(`downloaded recording ${recording.filename}`);
    } catch (err) {
      const message = err instanceof Error ? err.message : String(err);
      await convex.mutation(api.recordings.markFailed, { id: recording._id, error: message });
      failed += 1;
      await log.error(`failed to download requested recording ${recording.filename}`, {
        error: message,
      });
    }
  }

  return { downloaded, failed };
}

async function main() {
  console.log(
    `Starting DDPAI poller, interval ${config.pollIntervalMs}ms — idle until a camera session starts`,
  );

  const resetCount = await convex.mutation(api.downloadProgress.resetStale, {});
  if (resetCount > 0) {
    console.log(`cleared ${resetCount} stale "downloading" entries from a previous run`);
  }

  startControlServer({
    getState: () => state,
    triggerPoll: () => {
      pollOnce().catch((err) => console.error("manual poll failed", err));
    },
    startSession,
    endSession,
  });

  // No Wi-Fi watcher script exists yet to call /session/start, so bootstrap
  // automatically when there's exactly one registered camera — the common
  // single-camera case shouldn't require standing up network-change
  // detection first. Once a second camera is registered this no longer
  // applies, since the poller can't guess which one you're on.
  const cameras = await convex.query(api.cameras.list, {});
  if (cameras.length === 1) {
    console.log(`only one camera registered — auto-starting its session`);
    startSessionForCamera(cameras[0]);
  } else if (cameras.length === 0) {
    console.log("no cameras registered — add one in Settings, or POST /session/start once one exists");
  } else {
    console.log(
      `${cameras.length} cameras registered — waiting for POST /session/start (no auto-start with multiple cameras)`,
    );
  }

  await pollOnce();
  setInterval(() => {
    pollOnce().catch((err) => console.error("poll cycle failed", err));
  }, config.pollIntervalMs);
}

main().catch((err) => {
  console.error("poller crashed", err);
  process.exit(1);
});
